version: '3.5'

networks:
    traefik:
        external: true

volumes:
    portainer_data:
        driver: local

services:
    traefik:
        build:
            context: traefik
            args:
                - SELFSIGNED_CERTS=0
        command: --debug=${TRAEFIK_DEBUG} --logLevel=${TRAEFIK_LOG_LEVEL} --docker.domain=${TRAEFIK_DOMAIN}
        restart: unless-stopped
        environment:
            - GANDIV5_API_KEY=${TRAEFIK_GANDIV5_API_KEY}
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./traefik/conf/traefik.acme.toml:/etc/traefik/traefik.toml
            - ./traefik/ssl/acme/acme.json:/etc/ssl/acme/acme.json
        ports:
            - 127.0.0.1:80:80
            - 127.0.0.1:443:443
        networks:
            - traefik
        labels:
            - "traefik.enable=true"
            - "traefik.backend=traefik-dashboard.traefik"
            - "traefik.frontend.rule=Host:traefik-dashboard.${TRAEFIK_DOMAIN}"
            - "traefik.port=8080"

    portainer:
        image: portainer/portainer:latest
        command: -H unix:///var/run/docker.sock --no-auth
        restart: unless-stopped
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - portainer_data:/data
        networks:
            - traefik
        labels:
            - "traefik.enable=true"
            - "traefik.backend=portainer"
            - "traefik.frontend.rule=Host:portainer.${TRAEFIK_DOMAIN}"
            - "traefik.port=9000"
